### ISSUE TITLE
Allow for larger bot files

### ISSUE THREAD

**Issue by mjpieters** [inglesp/botany#3]
The client submits bots to the server as `application/x-www-form-urlencoded` data; this is a limited format that Django rightly restricts with a size limit.

However, that leaves bot files with limited space in the module. If the server were to accept bots as *files* however, larger modules could be submitted.

The client code would need to switch to using the `files` parameter:

```python
    submit_url = utils.get_setting("origin") + "/api/submit/"
    bot_name = os.path.basename(path)
    # optionally: verify bot code first, before submission
    # utils.read_bot_code(path)

    data = {
        "api_token": utils.get_setting("api_token"),
        "bot_name": bot_name,
    }
    with open(path) as bot_file:
        files = {'bot_code': bot_file}
        rsp = requests.post(submit_url, data=data, files=files)
```

and the server would need to use [`request.FILES['bot_code']`](https://docs.djangoproject.com/en/2.1/ref/request-response/#django.http.HttpRequest.FILES) to access the uploaded bot code.

**Comment by inglesp** [comment]
This is fixed in 87e52c4f86ecec27f2d4eba35016419b8b818d64.
