### ISSUE TITLE
Bug: house bots mislabeled as 'user :: housbotname' in botid/games view

### ISSUE THREAD

**Issue by mjpieters** [inglesp/botany#4]
When you look at the full list of games between bots, the opponent bot names are mangled. For example, on my recent bot list at https://botany18.pyconuk.org/bots/155/games/, I see

> As bot2 against Martijn Pieters : : anarchist.py (bot2 won)
> As bot1 against house : : anarchist.py (bot1 won) 

and

>  As bot1 against Jon Bannister : : anyboot.py (bot1 won)
> As bot2 against Martijn Pieters : : anyboot.py (bot2 won) 

My bot was not bot2 against *Martijn Pieters : : anarchist.py* or *Martijn Pieters : : anyboot.py*; that should be *Jon Bannister : : anarchist.py*, respectively.

**Comment by mjpieters** [comment]
Updated the report; this is not limited to house bots.

**Comment by inglesp** [comment]
Closed by #5.
