### ISSUE TITLE
Access to game moves from web UI

### ISSUE THREAD

**Issue by mjpieters** [inglesp/botany#6]
Currently, individual games are rendered as a series of tables, fully displaying the board for each step.

Can the move list be added for easy re-use? I want to be able to re-create games locally for better analysis and stepping through manually is a bit of a pain.

A simple 0-based numerical list would be great. 😄

**Comment by inglesp** [comment]
How about c07a233585a745cbb17b030da9e004cb3272cab4?

Eg https://botany18.pyconuk.org/games/138/

**Comment by mjpieters** [comment]
Exactly that! Thanks!
